### ISSUE TITLE
The "templates" directory is empty

### ISSUE THREAD

**Issue by titovm** [pixelmord/generator-drupaltheme#1]
So, does your generator create anything or is there a fault in my system (i'm on win and yeoman runs a bit sketchy here)?
I'm making many drupal themes and am iterested in working on/with this generator.

**Comment by pixelmord** [comment]
Sorry for getting back with so much delay, the Google mail sorted inbox drives me crazy :(

At the moment the generator will create no templates in the directory, but this feature is planned.
(See also the README - currently this is still version 0.0.x)

I'm thinking about giving a choice, if templates should be added, because it is not easy to cater for all needs and purposes. Most likely I will add a set of HTML5 templates that should suit a lot of projects.

**Comment by desmondmorris** [comment]
@pixelmord perhaps providing the default system template files would suffice.  This would give people a good starting point.  It would also be less to maintain.  I can take a stab and open a PR.

Thoughts?

**Comment by pixelmord** [comment]
@titovm @desmondmorris 
I know it took me forever :( , but now you'll get some HTML5 templates and preprocessing when you execute the generator. Have fun.
